services:
  db:
    image: postgres:15-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mi_blog_prueba
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mi_blog_prueba"]
      interval: 5s
      timeout: 30s
      retries: 5

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy